# Generated by Django 5.2.5 on 2025-10-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the doctor', max_length=100)),
                ('specialization', models.CharField(help_text='Medical specialization (e.g., Cardiology, Dermatology)', max_length=100)),
                ('location', models.CharField(help_text='City or area where the doctor practices', max_length=100)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('contact', models.CharField(help_text='Contact phone number', max_length=15)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
